### ISSUE TITLE
rel:createUnique()

### ISSUE THREAD

**Issue by alank64** [brikteknologier/seraph#153]
Is there a link/reference/issue as to why createUnique() was removed from 0.9.x? I'm just wondering if this would be good to document or if it was obvious to remove? Must have missed something, if so link this issue to it. Thanks.

**Comment by jonpacker** [comment]
createUnique used [legacy unique indexes](http://neo4j.com/docs/stable/rest-api-unique-indexes.html#rest-api-get-or-create-unique-node-create) which are deprecated now. createUnique was an alias to both `rel.index.getOrSaveUnique`/`rel.index.saveUniqueOrFail`, and these have not been removed, they have just been moved to `rel.legacyindex.getOrSaveUnique`/`rel.legacyindex.saveUniqueOrFail`. So if you really want to still use them, you still can, but I recommend updating your projects to use the new [uniqueness constraints](http://neo4j.com/docs/stable/rest-api-schema-constraints.html#rest-api-create-uniqueness-constraint) offered in neo4j 2+. Seraph [supports these](https://github.com/brikteknologier/seraph#constraints.uniqueness.create). The uniqueness is checked when you apply a label to a node, or if you are applying it within a cypher query, it is checked atomically by neo4j.

I should probably have documented where it went a little better. Any suggestion where it could be documented? I don't really want to have it on the method list, because it might be confusing considering that it doesn't exist anymore.
