### ISSUE TITLE
unpredictable return type from db.query

### ISSUE THREAD

**Issue by SQUARE-WAVES** [brikteknologier/seraph#176]
presently seraph makes an attempt to guess at the desired return type of particular kinds of queries when parsing query results,. Db.query can return an array or not depending on some very slight changes in your query. This is not documented well, and is in general a bad behavior as a person making queries doesn't necessarily know how many responses they can expect to get in advance of making the query, which then requires them to write extra boilerplate to test whether they got an array back. Or they have to shuffle their queries around to make sure they get things they want. As well, depending on what kind of value the aggregate or property being returned is you might end up with an array as the first column, which will prevent the result from being removed from the array.

For example, consider the following 2 queries
query 1:
MATCH (obj) WHERE id(obj)=10 RETURN obj.prop, obj

query 2:
MATCH (obj) WHERE id(obj)=10 RETURN obj,obj.prop

assuming there is a node with neo4j id 10, in the case of query 2 you will always receive and array of the form: [{"obj":{...}, "obj.prop":whatever the value of prop is}];

in the case of query 1, if prop is a string or a number or some primitive value you will get a result that looks like {obj.prop:..., obj:{...}}. If prop is an array, you will get [{obj.prop:[...], obj:{...}}]

I would recommend removing the check for a single object return and just always return an array. That way everyone always knows what they are getting no matter the query or the data.

**Comment by jonpacker** [comment]
I agree with you, I've wanted to fix it for a while—but I haven't had the time. If I remember correctly there's a fair about of rewriting that is caused by this change in `seraph-model` and `seraph-resource`, along with the fact that it could be a breaking change for some. So it's difficult to coordinate and get it done properly (but of course that doesn't mean that it shouldn't be done).

**Comment by SQUARE-WAVES** [comment]
Yeah, I can understand that. But isn't that what semver is there to deal with? Mark this change as a major version, cause it's definitiely a breaking change. And then just make sure model and resource know not to use it yet.

**Comment by jonpacker** [comment]
Although seraph-resource and seraph-model don't have seraph as an actual dependency, this could probably be solved with `peerDependencies`, yeah. I have just preferred to avoid using it because I find it to be a bit unpredictable. But that was a while ago, maybe it's better these days. The biggest problem here is definitely finding the time to do it, though :)

**Comment by SQUARE-WAVES** [comment]
well, from the point of view of seraph itself it's a small change, basically just delete the last else clause in _parseQueryResults in seraph.js. I'd be glad to submit a PR for it.

I don't know about seraph-model or seraph-resource, there also seems to be a thing called seraph-disposable, but it could be as easy as just throwing a var result = whatever[0] in a few spots.

**Comment by SQUARE-WAVES** [comment]
oh I guess I should close this.
