### ISSUE TITLE
Node creation error - 'Parentheses are required to identify nodes in pattern'

### ISSUE THREAD

**Issue by poluxus** [brikteknologier/seraph#201]
Hi.
I'm using neo4j 3 and i saw a similar problem but for deletion.

Here is my error message

>{ code: 'Neo.ClientError.Statement.SyntaxError',
  message: 'Parentheses are required to identify nodes in patterns, i.e. (Person0) (line 1, column 93 (offset: 92))\n"START Person0=node({Person0id})  MERGE (Person1:Person {muri: {Person1key}})  CREATE UNIQUE Person0-[__rel_Person1:FOLLOW]->Person1 SET __rel_Person1={__rel_Person1},Person1={Person1}  RETURN Person0,Person1,__rel_Person1"
 ^' }
(the pointer is under RETURN)

using neo4j 3.0.3 and seraph 0.14.4

Thanks in advance

**Comment by jonpacker** [comment]
Hey! It looks like this is a [seraph-model](https://github.com/brikteknologier/seraph-model) issue, and in particular one that was recently fixed. Could you try updating your seraph-model version and see if that fixes it? Otherwise, open an issue on the seraph-model repo. Or reopen this one if I'm wrong! Cheers.

**Comment by poluxus** [comment]
You were absolutely right.
Sorry to have bother you.
Thanks for the great work!!!
